version: '3.7'

services:
  app:
    container_name: app-dev2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "npm run iall && npm run startboth"